sudo: false
language: java
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
addons:
    apt:
        packages:
            - stunnel4
install:
  - make travis-install
script: make test
cache:
  directories:
    - $HOME/.m2
